ITAssessmentSystem/Controllers/ResultsController.cs
using ITAssessmentSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.Linq.Expressions;

namespace ITAssessmentSystem.Controllers
{
    [Authorize]
    public class ResultsController : Controller
    {
        //
        // GET: /Results/

        //Reference: https://stackoverflow.com/questions/12844779/search-on-all-fields-of-an-entity
        public ActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public ActionResult AllData(string param, int? page, string column, string sortOrder)
        {
            using (var context = new AssessmentEntities())
            {
                try
                {
                    IEnumerable<spASSESSMENT_RECORDS_Result> results = null;
                    param = string.IsNullOrEmpty(param) ? "" : param;
                    //sortOrder = string.IsNullOrEmpty(sortOrder) ? "" : sortOrder;
                    ViewBag.Order = "";
                    if (String.IsNullOrEmpty(column) && String.IsNullOrWhiteSpace(sortOrder))
                        results = getAllRecords(context, param).ToList();
                    else
                        results = SortTable(context, param, column, sortOrder).ToList();

                    var pageView = results.ToPagedList(page ?? 1, 5);
                    return View("_AllData", "AllData", pageView);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    ViewBag.ErrorMsg = "Unable to fetch the data due to bad url";
                    return View("Error");
                }
            }
        }

        public IQueryable<spASSESSMENT_RECORDS_Result> getAllRecords(AssessmentEntities context, string param)
        {
            return context.spASSESSMENT_RECORDS(param).AsQueryable();
        }

        public IQueryable<spASSESSMENT_RECORDS_Result> SortTable(AssessmentEntities context, string param, string column, string sortOrder)
        {

            ViewBag.Order = String.IsNullOrEmpty(sortOrder) ? "desc" : "";
            sortOrder = String.IsNullOrEmpty(sortOrder) ? "" : sortOrder;
            var results = context.spASSESSMENT_RECORDS(param).AsQueryable();
            Func<IQueryable<spASSESSMENT_RECORDS_Result>, Expression<Func<spASSESSMENT_RECORDS_Result, string>>, IOrderedQueryable<spASSESSMENT_RECORDS_Result>> orderBy;

            if (!sortOrder.Equals("desc"))
            {
                orderBy = Queryable.OrderBy;
            }
            else
            {
                orderBy = Queryable.OrderByDescending;
            }
            results = orderBy(results, spASSESSMENT_RECORDS_Result.Order(column))
               .ThenBy(searchResults => searchResults.OUTCOMES);
            return results;
        }
    }
}

ITAssessmentSystem/Views/Results/AllData.cshtml
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
@{
    ViewBag.Title = "Assessment Data";
    Layout = "~/Views/Shared/_AdministratorLayout.cshtml";
}
<h2>Assessment Data</h2>
@RenderBody()
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/unobtrusive")

ITAssessmentSystem/Views/Results/_AllData.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ITAssessmentSystem.Models.spASSESSMENT_RECORDS_Result>

<table class="table table-bordered">
    <tr>
        <th>
            @Html.ActionLink("Professor", "AllData", new { param = Request.QueryString["param"], page = 1, column = "Instructor", sortOrder = ViewBag.Order })
        </th>
        <th>
            @Html.ActionLink("Department", "AllData", new { param = Request.QueryString["param"], page = 1, column = "department", sortOrder = ViewBag.Order })
        </th>
        <th>
            @Html.ActionLink("Semester", "AllData", new { param = Request.QueryString["param"], page = 1, column = "semester", sortOrder = ViewBag.Order })
        </th>
        <th>
            @Html.ActionLink("Year", "AllData", new { param = Request.QueryString["param"], page = 1, column = "year", sortOrder = ViewBag.Order })
        </th>
        <th>
            @Html.ActionLink("Course", "AllData", new { param = Request.QueryString["param"], page = 1, column = "course", sortOrder = ViewBag.Order })
        </th>
        <th>
            @Html.ActionLink("Performance Indicator", "AllData", new { param = Request.QueryString["param"], page = 1, column = "performanceIndicator", sortOrder = ViewBag.Order })
        </th>
        <th>
            @Html.ActionLink("Topic", "AllData", new { param = Request.QueryString["param"], page = 1, column = "topic", sortOrder = ViewBag.Order })
        </th>
        <th>
            @Html.DisplayName("Poor")
        </th>
        <th>
            @Html.DisplayName("Developing")
        </th>
        <th>
            @Html.DisplayName("Developed")
        </th>
        <th>
            @Html.DisplayName("Exemplary")
        </th>
        <th>
            @Html.DisplayName("Actual Level")
        </th>
        <th>
            @Html.DisplayName("Expected Level")
        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.INSTRUCTOR_NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEPARTMENT_DESC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SEMESTER)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YEAR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.COURSE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PERFORMANCE_INDICATOR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TOPIC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.POOR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEVELOPING)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEVELOPED)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EXEMPLARY)
            </td>
            <td>
                @{
        ViewBag.ActualLevel = Math.Ceiling((double)((item.DEVELOPED + item.EXEMPLARY) /
        (double)(item.POOR + item.DEVELOPING + item.DEVELOPED + item.EXEMPLARY)) * 100);}
                @ViewBag.ActualLevel %
            </td>
            <td>@item.EXPECTATION_LEVEL</td>
            
        </tr>
    }
</table>
@Html.PagedListPager(Model, page => Url.Action("AllData", "Results",
    new
    {
        page,
        param = Request.QueryString["param"],
        column = Request.QueryString["column"],
        sortOrder = Request.QueryString["sortOrder"]
    }))