ITAssessmentSystem/Models/Assessment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

ITAssessmentSystem/Controllers/AssessmentController.cs
using ITAssessmentSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ITAssessmentSystem.Controllers
{
    public class AssessmentController : Controller
    {
        //
        // GET: /Assessment/
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Reference()
        {
            ViewBag.total = 0;
            string linkid;
            using (var context = new AssessmentEntities())
            {
                try
                {
                    linkid = Request.QueryString["linkid"].ToString();
                    var VerifyLink = context.ASSESSMENT_LINK.Where(link => link.RANDOM_STRING == linkid).ToList();

                    if (VerifyLink.Count == 1)
                    {
                        var linkDetails = VerifyLink.First();

                        var result = context.spRUBRICGETSEARCHRESULTS(linkDetails.DEPARTMENT_CD, linkDetails.OUTCOMES).ToList();
                        var rubRowID = result.Select(rubrowID => rubrowID.RUBRIC_ROWID.ToString()).ToList();
                        Session["RubRowIDS"] = rubRowID;
                        foreach (var item in rubRowID)
                        {
                            Session[item] = "0-0-0-0";
                        }
                        result.First().Instructor_EmailID = linkDetails.INSTRUCTOR_EMAILID;
                        return View(result);
                    }
                    else
                    {
                        ViewBag.ErrorMsg = "Invalid URL. Please check the Link again";
                        return View("Error");
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMsg = "Unable to fetch data. Please contact the Assessment officer";
                    return View("Error");
                }
            }

        }

        [HttpPost]

        public ActionResult Reference(ASSESSMENT_DATA assessedData)
        {
            bool status = false;
            using (var context = new AssessmentEntities())
            {
                try
                {
                    if (context.ASSESSMENT_DATA.Where(rdmstring => rdmstring.RANDOM_STRING == assessedData.RANDOM_STRING).ToList().Count != 0)
                    {
                        //link is already been used
                        //delete old records
                        context.spASSESSMENT_DELETE_OLD_RECORDS(assessedData.RANDOM_STRING);
                        context.SaveChanges();
                    }

                    foreach (var item in Session["RubRowIDS"] as List<String>)
                    {
                        string sessionData = Session[item].ToString();
                        String[] data = sessionData.Split('-');
                        assessedData.RUBRIC_ROWID = Int16.Parse(item);
                        assessedData.POOR = Int16.Parse(data[0]);
                        assessedData.DEVELOPING = Int16.Parse(data[1]);
                        assessedData.DEVELOPED = Int16.Parse(data[2]);
                        assessedData.EXEMPLARY = Int16.Parse(data[3]);
                        if (assessedData.POOR + assessedData.DEVELOPING + assessedData.DEVELOPED + assessedData.EXEMPLARY != 0)
                        {
                            context.ASSESSMENT_DATA.Add(assessedData);
                            context.SaveChanges();

                            context.spLINK_UPDATESTATUS(assessedData.RANDOM_STRING, false);
                            context.SaveChanges();

                        }
                        else
                        {
                            ViewBag.ErrorMsg = "Please input at least one record for assessment";
                            return View("Error");
                        }
                    }
                    return View("Success");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    ViewBag.ErrorMsg = "Please complete all form fields.";
                    return View("Error");
                }
            }
        }

        public bool VerifyInstructorInput(FormCollection formCollection, List<String> RubRowIDS)
        {
            bool isValid = true;
            if (RubRowIDS != null)
            {
                foreach (var item in RubRowIDS)
                {
                    if (String.IsNullOrEmpty(formCollection[item]))
                    {
                        isValid = false;
                    }
                }
            }
            else
            {
                isValid = false;
            }
            return isValid;
        }


        [HttpPost]
        
        public ActionResult InsertRecord(FormCollection f)
        {
            if (VerifyInstructorInput(f, Session["RubRowIDS"] as List<String>))
            {
                foreach (var item in Session["RubRowIDS"] as List<String>)
                {
                    try
                    {
                        var userInput = Int16.Parse(f[item]);
                        string sessionData = Session[item].ToString();
                        String[] data = sessionData.Split('-');
                        var result = Int16.Parse(data[userInput]) + 1;
                        data[userInput] = result.ToString();
                        sessionData = data[0] + "-" + data[1] + "-" + data[2] + "-" + data[3];
                        Session[item] = sessionData;
                        ViewBag.total = Int16.Parse(data[0]) + Int16.Parse(data[1]) + Int16.Parse(data[2]) + Int16.Parse(data[3]);
                    }

                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                        ViewBag.ErrorMsg = "Something went wrong. Please retry.";
                        return View("Error");
                    }
                }
            }
            return PartialView("_InstructorInput");
        }

        public ActionResult Reset()
        {
            foreach (var item in Session["RubRowIDS"] as List<String>)
            {
                Session[item] = "0-0-0-0";
            }
            return PartialView("_InstructorInput");
        }
    }
}

ITAssessmentSystem/Views/Assessment/Reference.cshtml
@model IEnumerable<ITAssessmentSystem.Models.spRUBRICGETSEARCHRESULTS_Result>

@{
    ViewBag.Title = "Fill";
}

<h2>Fill</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PERFORMANCE_INDICATOR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TOPIC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.POOR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DEVELOPING)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DEVELOPED)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EXEMPLARY)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PERFORMANCE_INDICATOR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TOPIC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.POOR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEVELOPING)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEVELOPED)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EXEMPLARY)
            </td>

        </tr>
    }

</table>

<h1>Your input</h1>

@Html.Partial("_InsertData", Model)


@Scripts.Render("~/bundles/jquery")
<script>
   
</script>

ITAssessmentSystem/Views/Assessment/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>
<h4>Your record has been successfully inserted</h4>
<h2>Thank you.</h2>

ITAssessmentSystem/Views/Assessment/Temp.cshtml
@model ITAssessmentSystem.Models.ASSESSMENT_DATA


@foreach (var item in ViewBag.rubs
                as List<string>)
{
    <p>@item</p>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ASSESSMENT_DATA</h4>
        <hr />
        @Html.ValidationSummary(true)



        <div class="form-group">
            @Html.LabelFor(model => model.OUTCOMES, "OUTCOMES", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("OUTCOMES", Request.QueryString["outcome"])
                @Html.ValidationMessageFor(model => model.OUTCOMES)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DEPARTMENT, "DEPARTMENT", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("DEPARTMENT", Request.QueryString["outcome"])
                @Html.ValidationMessageFor(model => model.DEPARTMENT)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PROF_EMAILID, "PROF_EMAILID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("PROF_EMAILID", String.Empty)
                @Html.ValidationMessageFor(model => model.PROF_EMAILID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SEMESTER, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SEMESTER)
                @Html.ValidationMessageFor(model => model.SEMESTER)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.COURSE, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.COURSE)
                @Html.ValidationMessageFor(model => model.COURSE)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PERFORMANCE_INDICATOR, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PERFORMANCE_INDICATOR)
                @Html.ValidationMessageFor(model => model.PERFORMANCE_INDICATOR)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TOPIC, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TOPIC)
                @Html.ValidationMessageFor(model => model.TOPIC)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.POOR, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.POOR)
                @Html.ValidationMessageFor(model => model.POOR)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DEVELOPING, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DEVELOPING)
                @Html.ValidationMessageFor(model => model.DEVELOPING)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DEVELOPED, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DEVELOPED)
                @Html.ValidationMessageFor(model => model.DEVELOPED)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EXEMPLARY, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EXEMPLARY)
                @Html.ValidationMessageFor(model => model.EXEMPLARY)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITAssessmentSystem/Views/Assessment/_AssessmentInfo.cshtml
@model ITAssessmentSystem.Models.ASSESSMENT_DATA

<h2>Hi</h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ASSESSMENT_DATA</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.RUBRIC_ROWID, "RUBRIC_ROWID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RUBRIC_ROWID", String.Empty)
                @Html.ValidationMessageFor(model => model.RUBRIC_ROWID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OUTCOMES, "OUTCOMES", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OUTCOMES", String.Empty)
                @Html.ValidationMessageFor(model => model.OUTCOMES)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DEPARTMENT, "DEPARTMENT", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DEPARTMENT", String.Empty)
                @Html.ValidationMessageFor(model => model.DEPARTMENT)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PROF_EMAILID, "PROF_EMAILID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PROF_EMAILID", String.Empty)
                @Html.ValidationMessageFor(model => model.PROF_EMAILID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SEMESTER, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SEMESTER)
                @Html.ValidationMessageFor(model => model.SEMESTER)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.COURSE, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.COURSE)
                @Html.ValidationMessageFor(model => model.COURSE)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PERFORMANCE_INDICATOR, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PERFORMANCE_INDICATOR)
                @Html.ValidationMessageFor(model => model.PERFORMANCE_INDICATOR)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TOPIC, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TOPIC)
                @Html.ValidationMessageFor(model => model.TOPIC)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.POOR, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.POOR)
                @Html.ValidationMessageFor(model => model.POOR)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DEVELOPING, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DEVELOPING)
                @Html.ValidationMessageFor(model => model.DEVELOPING)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DEVELOPED, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DEVELOPED)
                @Html.ValidationMessageFor(model => model.DEVELOPED)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EXEMPLARY, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EXEMPLARY)
                @Html.ValidationMessageFor(model => model.EXEMPLARY)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITAssessmentSystem/Views/Assessment/_InsertData.cshtml
@model IEnumerable<ITAssessmentSystem.Models.spRUBRICGETSEARCHRESULTS_Result>

<form id="xxx" method="post">

    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.Hidden("RANDOM_STRING", Request.QueryString["linkid"])
        <div class="form-group">
            @Html.Label("Course", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Course")
                @Html.Label("For Example - IT 478")
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Department", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Department", Model.First().DEPARTMENT_CD, new { @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Semester", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextBox("Semester")*@
                @Html.DropDownList("Semester", new List<SelectListItem>
                 {
                    new SelectListItem{ Text="FALL", Value = "FALL " },
                    new SelectListItem{ Text="SPRING", Value = "SPRING " },
                    new SelectListItem{ Text="SUMMER", Value = "SUMMER " },

                 })
                @Html.DropDownList("YEAR", new List<SelectListItem>
                 {
                    new SelectListItem{ Text="2015", Value = "2015" },
                    new SelectListItem{ Text="2016", Value = "2016" },
                    new SelectListItem{ Text="2017", Value = "2017" },
                    new SelectListItem{ Text="2018", Value = "2018" },
                    new SelectListItem{ Text="2019", Value = "2019" },
                    new SelectListItem{ Text="2020", Value = "2020" }
                 })

            </div>
        </div>
        <div class="form-group">
            @Html.Label("Instructor Email ID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Instructor_Email", Model.First().Instructor_EmailID, new { @readonly = "readonly" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Outcome", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Outcome", Model.First().OUTCOMES, new { @readonly = "readonly" })
            </div>
        </div>

        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        Topic
                    </th>
                    <th>
                        Poor
                    </th>
                    <th>
                        Developing
                    </th>
                    <th>
                        Developed
                    </th>
                    <th>
                        Exemplary
                    </th>
                </tr>
            </thead>

            <div id="reset">

                @foreach (var item in Model
                as List<ITAssessmentSystem.Models.spRUBRICGETSEARCHRESULTS_Result>)
                {
                    <tr>
                        <td>
                            @item.TOPIC
                        </td>
                        <td>
                            <input type="radio" name="@item.RUBRIC_ROWID" value="0" class="rubs" />
                        </td>
                        <td>
                            <input type="radio" name="@item.RUBRIC_ROWID" value="1" class="rubs" />
                        </td>
                        <td>
                            <input type="radio" name="@item.RUBRIC_ROWID" value="2" class="rubs" />
                        </td>
                        <td>
                            <input type="radio" name="@item.RUBRIC_ROWID" value="3" class="rubs" />
                        </td>
                    </tr>
                }

            </div>
        </table>
        <br />
        <div class="form-group">
            <div class="col-md-2">
                <input type="button" value="Insert Record" class="btn btn-primary" onclick="submitRecord(this);" />
            </div>
            <div class="col-md-2">
                @Ajax.ActionLink("Reset All Record", "Reset", "Assessment", new AjaxOptions { UpdateTargetId = "currentRecord" }, new { @class = "btn btn-danger" })

            </div>
            <div class="col-md-2">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>

    </div>
</form>

<div id="currentRecord">
    @Html.Partial("_InstructorInput")
</div>

@Scripts.Render("~/bundles/jquery")
<script>
    function submitRecord(btnClicked) {
        var $form = $(btnClicked).parents('form');
        var tbl = $('#currentRecord');
        $.ajax({
            type: "POST",
            url: '@Url.Action("InsertRecord", "Assessment")',
            data: $form.serialize(),
            error: function (xhr, status, error) {
                //do something about the error
            },
            success: function (response) {
                //resets the previous selection for entering the next input
                $('input[class="rubs"]').attr('checked', false);
                tbl.empty().append(response);
            }
        });
    }

    function ResetRecord() {

        var reply = confirm("Are you sure?");
        if (reply) {
            var tbl = $('#currentRecord');
            $.ajax({
                type: "GET",
                url: '@Url.Action("Reset", "Assessment")',
                error: function (xhr, status, error) {
                    //do something about the error
                },
                success: function (response) {
                    //do something with response
                    tbl.empty().append(response);
                }
            });
        }
    }

</script>

ITAssessmentSystem/Views/Assessment/_InstructorInput.cshtml
<h1>Output</h1>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Poor</th>
            <th>Developing</th>
            <th>Developed</th>
            <th>Exemplary</th>
        </tr>
    </thead>
    <span id="currentRecord">
        @foreach (var item in Session["RubRowIDS"]
                as List<string>)
        {
            <tr>

                <div id="res">
                    <td>@Session[item].ToString().Split('-')[0]</td>
                    <td>@Session[item].ToString().Split('-')[1]</td>
                    <td>@Session[item].ToString().Split('-')[2]</td>
                    <td>@Session[item].ToString().Split('-')[3]</td>
                </div>

            </tr>
        }
    </span>
</table>

<h3>Total Student Records: @ViewBag.total</h3>

ITAssessmentSystem/Views/Assessment/_PartialResults.cshtml
<h2>@ViewBag.TempResults</h2>