ITAssessmentSystem/Controllers/InstructorController.cs
using ITAssessmentSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITAssessmentSystem.Controllers
{
     [Authorize]
    public class InstructorController : Controller
    {
        //
        // GET: /Instructor/
        
        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insert(USER_INFO userinfo)
        {
            using (var context = new AssessmentEntities())
            {
                try
                {
                    var result = context.spInstructorAddNew(userinfo.INSTRUCTOR_NAME, userinfo.INSTRUCTOR_EMAILID);
                    return RedirectToAction("AllInstructors");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    ViewBag.ErrorMsg = "Instructor Email ID already exist in the Database. Please use different one.";
                    return View("Error");
                }
            }
        }

        public ActionResult AllInstructors()
        {
            using (var context = new AssessmentEntities())
            {
                try
                {
                    var result = (IEnumerable<spINSTRUCTORGETALLRECORDS_Result>)context.spINSTRUCTORGETALLRECORDS().ToList();
                    return View(result);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    ViewBag.ErrorMsg = "Something went wrong while fetching. Please retry after some time.";
                    return View("Error");
                }
            }

        }


        public ActionResult Edit(string email)
        {
            using (var context = new AssessmentEntities())
            {
                try
                {
                    var result = context.spINSTRUCTORGETDETAILS(email).SingleOrDefault();
                    return View(result);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    ViewBag.ErrorMsg = "Unable to fetch the record. Please retry again.";
                    return View("Error");
                }
            }

        }

        [HttpPost]
        [ActionName("EditRecord")]
        public ActionResult Edit_Save(USER_INFO userinfo)
        {
            using (var context = new AssessmentEntities())
            {
                try
                {
                    var i = context.spINSTRUCTOREDIT(userinfo.INSTRUCTOR_EMAILID, userinfo.INSTRUCTOR_NAME);
                    return RedirectToAction("AllInstructors");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    ViewBag.ErrorMsg = "Unable to edit the record. Please retry again.";
                    return View("Error");
                }
            }
        }

        [HttpPost]
        [ActionName("DeleteRecord")]
        public ActionResult Delete(string email)
        {
            using (var context = new AssessmentEntities())
            {
                try
                {
                    var result = context.spINSTRUCTORDELETE(email);
                    return RedirectToAction("AllInstructors");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    ViewBag.ErrorMsg = "The Record does not exist or has already been deleted.";
                    return View("Error");
                }
               
            }
        }
    }
}

ITAssessmentSystem/Views/Instructor/AllInstructors.cshtml
@model IEnumerable<ITAssessmentSystem.Models.spINSTRUCTORGETALLRECORDS_Result>
@{
    ViewBag.Title = "All Instructors";
    Layout = "~/Views/Shared/_AdministratorLayout.cshtml";
}
<h2>All Instructors List</h2>

@Html.ActionLink("Add New Instructor", "Insert", "Instructor", new { @class = "btn btn-primary" })
<br/>
<br />
<table class="table table-hover table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.INSTRUCTOR_NAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.INSTRUCTOR_EMAILID)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        using (Html.BeginForm("DeleteRecord", "Instructor", new { email = item.INSTRUCTOR_EMAILID }))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.INSTRUCTOR_NAME)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.INSTRUCTOR_EMAILID)
                </td>
                <td>
                    @Html.ActionLink("EditRecord", "Edit", new { email = item.INSTRUCTOR_EMAILID }, new { @class = "btn btn-primary" }) |
                    <input type="submit" value="Delete" class="btn btn-danger" onclick=" confirmdelete();" />
                </td>
            </tr>
        }
    }
</table>
<script>
    function confirmDelete() {
        var reply = confirm("Are you sure?");
        if (reply)
            return true;
        else
            return false;
    }

</script>

ITAssessmentSystem/Views/Instructor/Edit.cshtml
@model ITAssessmentSystem.Models.spINSTRUCTORGETDETAILS_Result

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_InstructorLayout.cshtml";
}

<h2>Edit Instructor's Details</h2>


@using (Html.BeginForm("EditRecord", "Instructor", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Instructor Information</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.Label("Instructor Email ID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.INSTRUCTOR_EMAILID)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Instructor Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INSTRUCTOR_NAME)
                @Html.ValidationMessageFor(model => model.INSTRUCTOR_NAME)
            </div>
        </div>

        @Html.HiddenFor(model => model.INSTRUCTOR_EMAILID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AllInstructors")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITAssessmentSystem/Views/Instructor/Insert.cshtml
@model ITAssessmentSystem.Models.USER_INFO

@{
    ViewBag.Title = "Insert";
    Layout = "~/Views/Shared/_InstructorLayout.cshtml";
}

<h2>Insert New Record</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Instructor Information</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.INSTRUCTOR_NAME, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INSTRUCTOR_NAME)
                @Html.ValidationMessageFor(model => model.INSTRUCTOR_NAME)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INSTRUCTOR_EMAILID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INSTRUCTOR_EMAILID)
                @Html.ValidationMessageFor(model => model.INSTRUCTOR_EMAILID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}